class GardeRobe
  @largeur: Integer

  def combinaisons: -> Array[Combinaison]

  private

  def combinaisons_avec: -> Array[Combinaison]
  def combinaisons_avec_m_fois: -> Array[Combinaison]
  def combiner: -> Combinaison
  def fit?: -> bool
  def max_elements: -> Integer
end